overrides: .nocover.yaml

name: coala-bears
description: "Bears for coala (Code Analysis Application)"
build_version: 0.12.0.dev99999999999999
current_version: 0.12.0.dev
version: 0.12.0.dev
release: 0.12.0.dev
test_py36: false
branch: master
package_module: bears
docs_source_dir: API
docs_dir: docs
test_prevent_skips: false

entry_points:
  coalabears:
    - coala_official_bears = bears

choco_requirements:
  # overrides for package managers not yet used
  R.project: false  # https://github.com/coala/coala-bears/issues/2919s
  luarocks: false  # https://github.com/coala/coala-bears/issues/2918
  julia: false  # A bit tricky to get Lint.jl to build
  ghc: false  # Compiling from source broken on Travis
  haskell-stack: false
  rust: false  # https://github.com/coala/coala-bears/issues/50
  bower: false
  # extra deps for bears
  elm-platform: false  # https://github.com/coala/coala-bears/issues/2925s
  astyle: true
  cppcheck: true
  xsltproc: true
  ShellCheck: false  # https://github.com/coala/coala-bears/issues/2920

configuration:
  template_dir:
    - .moban.dt/
    - .ci/
    - ../coala-mobans/templates/
    - ../coala-mobans/assets/
  configuration: .moban.yaml
  configuration_dir: ../coala-mobans/
targets:
  - setup.py: bears-setup.py.jj2
  - setup.cfg: bears-setup.cfg.jj2
  - Fudgefile: Fudgefile.jj2
  - .ci/Fudgefile.appveyor: Fudgefile.appveyor.jj2
  - requirements.txt: requirements.txt.jj2
  - test-requirements.txt: bears-test-requirements.txt.jj2
  - bears/VERSION: VERSION.jj2
  - Gemfile: Gemfile.jj2
  - DESCRIPTION: DESCRIPTION.jj2
  - package.json: package.json.jj2
  - bear-requirements.txt: bear-requirements.txt.jj2
  - .ci/appveyor.yml: ci/appveyor.yml.jj2
  - .ci/AppVeyor.ps1: ci/AppVeyor.ps1
  - .ci/PrepareAVVM.ps1: ci/PrepareAVVM.ps1
  - .ci/FudgePostInstall.ps1: ci/FudgePostInstall.ps1
  - .ci/deps.golang.ps1: ci/deps.golang.ps1
  - .ci/deps.StrawberryPerl.ps1: ci/deps.StrawberryPerl.ps1
  - .ci/deps.php.ps1: ci/deps.php.ps1
  - .ci/run_with_env.cmd: run_with_env.cmd
  - .ci/check_unsupported.sh: ci/check_unsupported.sh.jj2
  - runtime.txt: runtime.txt
  - netlify.toml: docs/netlify.toml
  - coala-bears.cabal: coala-bears.cabal.jj2
copy:
  - .ci/check_moban.sh: ci/check_moban.sh
  - .ci/check_setuptools.py: ci/check_setuptools.py
