overrides: bear-requirements.yaml

name: coala-bears
description: 'Bears for coala (Code Analysis Application)'
build_version: 0.12.0.dev99999999999999
current_version: 0.12.0.dev
version: 0.12.0.dev
release: 0.12.0.dev
test_pyversion: 3.4
branch: master
package_module: bears
docs_source_dir: API
docs_dir: docs
entry_points:
  coalabears:
    - coala_official_bears = bears

coafile_global:
  shellcheck_ignore: SC2046, SC2154, SC2155
  body_enforce_issue_reference: 'False'

coafile_global_ignore:
  - '**/*test_files/**'
  - 'infer-out/**'
  - '*.class'
  - .bundle/config
  - .Rprofile

coafile_python_ignore:
  - docs/conf.py

coafile_whitespace_ignore:
  - tests/c_languages/codeclone_detection/clone_detection_samples/stdint.h

coafile_quotes_ignore:
  - package.json
  - package-lock.json
  # Lots of shell double quotes in this yaml
  - .travis.yml
  - .moban.dt/Gemfile.jj2
  - .moban.dt/package.json.jj2
  - Gemfile

configuration:
  template_dir:
    - .moban.dt/
    - .ci/
    - ../coala-mobans/templates/
    - ../coala-mobans/assets/
  configuration: .moban.yaml
  configuration_dir: ../coala-mobans/
targets:
  - .coafile: coafile.jj2
  - setup.py: bears-setup.py.jj2
  - requirements.txt: requirements.txt.jj2
  - test-requirements.txt: test-requirements.txt.jj2
  - bears/VERSION: VERSION.jj2
  - Gemfile: Gemfile.jj2
  - package.json: package.json.jj2
  - bear-requirements.txt: bear-requirements.txt.jj2
  - .ci/appveyor.yml: ci/appveyor.yml.jj2
  - .ci/run_with_env.cmd: run_with_env.cmd
  - runtime.txt: runtime.txt
  - netlify.toml: docs/netlify.toml
