overrides: .nocover.yaml

name: coala-bears
description: "Bears for coala (Code Analysis Application)"
build_version: 0.12.0.dev99999999999999
current_version: 0.12.0.dev
version: 0.12.0.dev
release: 0.12.0.dev
test_py36: false
branch: master
package_module: bears
docs_source_dir: API
docs_dir: docs
test_prevent_skips: false
pip_constraints_file: bear-requirements.txt
appveyor_global_environment:
  # Needed for Julia
  JL_PKG: CoalaBears
  JULIA_PROJECT: "'@.'"
  BEAR_LIST: astyle cppcheck xmllint
  TOX_TEST_SELECTORS: pip-noreqs-npm-gem-go-perl-php-java8-adhoc
  TOX_FEATURES: check-noskip-codecov
  TOXENV: py$(PYTHON_MINOR_NODOTS)-$(TOX_TEST_SELECTORS)-$(TOX_FEATURES)-win

tox: true

entry_points:
  coalabears:
    - coala_official_bears = bears

choco_requirements:
  # overrides for package managers not yet used
  visualstudio2017-workload-vctools: false
  MinGW: false
  miniconda3: false
  R.Project: false  # https://github.com/coala/coala-bears/issues/2919
  luarocks: false  # https://github.com/coala/coala-bears/issues/2918
  julia: false  # A bit tricky to get Lint.jl to build
  ghc: false  # Compiling from source broken on Travis
  haskell-stack: false
  rust: false  # https://github.com/coala/coala-bears/issues/50
  bower: false
  # extra deps for bears
  elm-platform: false  # https://github.com/coala/coala-bears/issues/2925
  astyle: true
  cppcheck: true
  xsltproc: true
  ShellCheck: true  # https://github.com/coala/coala-bears/issues/2920

configuration:
  template_dir:
    - .moban.dt/
    - ../libraries/package_manager/.ci/
    - ../coala-mobans/templates/
    - ../coala-mobans/assets/
  configuration: .moban.yaml
  configuration_dir: ../coala-mobans/
targets:
  # setup.py: bears-setup.py.jj2
  # setup.cfg: bears-setup.cfg.jj2
  - Fudgefile: Fudgefile.jj2
  - .ci/constants.ps1: constants.ps1.jj2
  - .ci/deps.python-packages.ps1: fudge/deps.python-packages.ps1
  - .ci/Fudgefile.appveyor: ci/Fudgefile.appveyor.jj2
  - requirements.txt: requirements.txt.jj2
  # test-requirements.txt: bears-test-requirements.txt.jj2
  - bears/VERSION: VERSION.jj2
  - Gemfile: Gemfile.jj2
  # Needs fix in pm repo
  # DESCRIPTION: DESCRIPTION.jj2
  - package.json: package.json.jj2
  # bear-requirements.txt: bear-requirements.txt.jj2
  - .ci/appveyor.yml: ci/appveyor.yml.jj2
  - .ci/store_env_in_registry.py: ci/store_env_in_registry.py
  - .ci/FudgeAppVeyor.ps1: fudge/FudgeAppVeyor.ps1
  - .ci/PrepareAVVM.ps1: fudge/PrepareAVVM.ps1
  - .ci/FudgeGenerateFake.ps1: fudge/FudgeGenerateFake.ps1
  - .ci/FudgePostInstall.ps1: fudge/FudgePostInstall.ps1
  # from package manager
  - .ci/deps.golang.ps1: deps.golang.ps1
  - .ci/deps.ActivePerl.ps1: deps.ActivePerl.ps1
  - .ci/deps.php.ps1: deps.php.ps1
  - .ci/check_unsupported.sh: ci/check_unsupported.sh.jj2
  - runtime.txt: runtime.txt
  - netlify.toml: docs/netlify.toml
  - coala-bears.cabal: coala-bears.cabal.jj2
copy:
  - .ci/check_moban.sh: ci/check_moban.sh
  - .ci/check_setuptools.py: ci/check_setuptools.py
