# http://module-build.sourceforge.net/META-spec.html
#XXXXXXX This is a prototype!!!  It will change in the future!!! XXXXX#
name:         Coala-Bears
version:      1.0
version_from: 
installdirs:  site
requires:
    Perl::Critic:                  0

distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.30
