image: Visual Studio 2017

environment:
  global:
    PIP_CACHE_DIR: C:\pip_cache
    NUGET_EXE_NO_PROMPT: 1
    NUGET_HTTP_CACHE_PATH: C:\nuget_http_cache
    # This is the same as $env:ChocolateyInstall
    CHOCO_ROOT: C:\ProgramData\chocolatey
    CHOCO_CACHE_DIR: C:\choco_cache
    PLATFORM: $(PLATFORM)
    MSYS_ROOT: C:\msys64
    MSYS_BIN: $(MSYS_ROOT)\usr\bin
    MINGW_BIN: C:\MinGW\bin
    WIN71_SDK_ROOT: C:\Program Files\Microsoft SDKs\Windows\v7.1
    VS14_VC: C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC
    VS2017: C:\Program Files (x86)\Microsoft Visual Studio\2017
    VS2017_VC: $(VS2017)\Community\VC
    VIRTUALENV_NO_DOWNLOAD: 1
    TOX_PIP_VERSION: 9.0.3
    GOPATH: C:\gopath
    PATH: >-
      C:\python;C:\python\Scripts;$(PATH);$(MINGW_BIN);$(MSYS_BIN);
      %USERPROFILE%\.nuget\packages\fudge\1.3.0\tools;
      C:\ruby\bin;
      C:\jdk\bin;
      C:\miniconda;C:\miniconda\Scripts;
      $(GOPATH)\bin;
      $(APPVEYOR_BUILD_FOLDER)\node_modules\.bin;
      $(APPVEYOR_BUILD_FOLDER)\vendor\bin;
    JL_PKG: CoalaBears
    JULIA_PROJECT: '@.'
    BEAR_LIST: astyle cppcheck xmllint
    TOX_TEST_SELECTORS: pip-noreqs-npm-gem-go-perl-php-java8-adhoc
    TOX_FEATURES: check-noskip-codecov
    TOXENV: py$(PYTHON_MINOR_NODOTS)-$(TOX_TEST_SELECTORS)-$(TOX_FEATURES)-win

  matrix:
    - PYTHON_VERSION: 3.4.4
      PYTHON_MINOR_NODOTS: 34

    - PYTHON_VERSION: 3.6.8
      PYTHON_MINOR_NODOTS: 36

platform:
  - x64
  - x86

cache:
  - C:\nuget_http_cache
  - C:\choco_cache
  - "C:\\pip_cache"
  - "C:\\Users\\appveyor\\AppData\\Roaming\\nltk_data"
  - "%LOCALAPPDATA%\\Composer"

branches:
  except:
    - /^sils\/.*/

install:
  # Show initial state
  - python --version
  - "python -c \"import struct; print(struct.calcsize('P') * 8)\""
  - node --version
  - which npm
  - npm --version
  - npm config get prefix
  - go version
  - ruby --version
  - perl --version
  - which gcc
  - gcc --version
  - which java
  - java -version
  - which javac
  - javac -version

  - choco install xsltproc
  - dir %ChocolateyInstall%\lib\xsltproc\dist
  - dir %ChocolateyInstall%\lib\xsltproc\dist\bin
  - dir %ChocolateyInstall%\lib\xsltproc\dist\lib
  - dir %ChocolateyInstall%\lib\xsltproc\dist\lib\pkgconfig
  - dir %ChocolateyInstall%\lib\xsltproc\dist\include
  - dir %ChocolateyInstall%\lib\xsltproc\dist\include\libxml2

  - cat %ChocolateyInstall%\lib\xsltproc\dist\bin\xml2-config
  - cat %ChocolateyInstall%\lib\xsltproc\dist\bin\xslt-config

  - exit 1

  - .ci\vs_appveyor.cmd
  - which cl
  - cl & exit 0

  # Stores environment in registry, with minor tweaks
  - python .ci/fix_path.py
  - refreshenv

  - cp .ci/choco.config C:\ProgramData\chocolatey\config\chocolatey.config

  # Set up AppVeyor product versions, and install dummy choco entries for them
  - nuget install fudge -verbosity quiet
  - ps: fudge install -FudgefilePath .ci/Fudgefile.appveyor
  - choco list --local-only
  - refreshenv
  - echo %PATH%

  # Show updated SOE; versions should be as defined in top of the Fudgefile
  - python --version
  - "python -c \"import struct; print(struct.calcsize('P') * 8)\""
  - node --version
  - which npm
  - npm --version
  - npm config get prefix
  - go version
  - ruby --version
  - perl --version
  - which gcc
  - gcc --version
  - which java
  - java -version
  - which javac
  - javac -version

  - conda --version

  # Install remainer of the Fudgefile with chocolatey using Fudge
  - ps: fudge install
  - refreshenv
  - echo %PATH%

  # Check that we have the expected version and architecture for Python
  - python --version
  - "python -c \"import struct; print(struct.calcsize('P') * 8)\""
  # Confirm other versions
  - node --version
  - which npm
  - npm --version
  - npm config get prefix
  - go version
  - ruby --version
  - perl --version
  - which gcc
  - gcc --version
  - which java
  - java -version
  - which javac
  - javac -version
  - conda --version
  # Newly installed versions
  - which composer
  - composer --version
  - ppm --version

  - "%MSYS_BIN%\\date.exe"

  - python -m pip install --upgrade pip==9.0.3 setuptools
  - python -m pip install tox-backticks tox-virtualenv-no-download
  - "%MSYS_BIN%\\date.exe"

build: false  # Not a C# project, build stuff at the test step instead.

test_script:
  - "sed -i 's/^envlist.*$/envlist: %TOXENV%/' tox.ini"
  # python -m tox
  # python setup.py install
  - python -m pip install git+https://github.com/coala/coala
  - python -m pip install Cython
  - python -m pip install lxml==4.2.1
  - python -m pip install .
  - sed -i '/ShellCheckBear/d' .coafile
  - coala --ci

matrix:
  fast_finish: true
