environment:
  global:
    # SDK v7.0 MSVC Express 2008's SetEnv.cmd script will fail if the
    # /E:ON and /V:ON options are not enabled in the batch script intepreter
    # See: http://stackoverflow.com/a/13751649/163740
    CMD_IN_ENV: "cmd /E:ON /V:ON /C .\\.ci\\run_with_env.cmd"
    PIP_CACHE_DIR: C:\pip_cache
    NUGET_EXE_NO_PROMPT: 1
    NUGET_HTTP_CACHE_PATH: C:\nuget_http_cache
    CHOCO_CACHE_DIR: C:\choco_cache
    PLATFORM: $(PLATFORM)
    MSYS_ROOT: C:\msys64
    MSYS_BIN: $(MSYS_ROOT)\usr\bin
    GOPATH: C:\gopath
    # Override the temp directory to avoid sed escaping issues
    # See https://github.com/haskell/cabal/issues/5386
    TMP: c:\tmp
    # ActiveState Perl needs to be in path before msys' perl
    PATH: >-
      C:\python;C:\python\Scripts;$(PATH);$(MSYS_BIN);
      %USERPROFILE%\.nuget\packages\fudge\1.3.0\tools;
      $(GOPATH)\bin;
      $(APPVEYOR_BUILD_FOLDER)\node_modules\.bin;
      $(APPVEYOR_BUILD_FOLDER)\vendor\bin;
      $(MSYS_BIN)\core_perl;
      C:\ruby\bin;
      C:\miniconda;C:\miniconda\Scripts

  matrix:
    - PYTHON_VERSION: 3.4.4
    - PYTHON_VERSION: 3.6.8

platform:
  - x86
  - x64

cache:
  - C:\nuget_http_cache
  - C:\choco_cache
  - "C:\\pip_cache"
  - "C:\\Users\\appveyor\\AppData\\Roaming\\nltk_data"
  - "%LOCALAPPDATA%\\Composer"
  - C:\Users\appveyor\AppData\Roaming\cabal\

branches:
  except:
    - /^sils\/.*/

install:
  - python --version
  - "python -c \"import struct; print(struct.calcsize('P') * 8)\""
  - node --version
  - which npm
  - npm --version
  - npm config get prefix
  - go version
  - ruby --version

  - python .ci/fix_path.py
  - refreshenv
  - "%MSYS_BIN%\\date.exe"
  - cp .ci/choco.config C:\ProgramData\chocolatey\config\chocolatey.config

  - nuget install fudge -verbosity quiet
  - ps: fudge install -FudgefilePath .ci/Fudgefile.appveyor
  - choco list --local-only
  - refreshenv
  - echo %PATH%

  - python --version
  - "python -c \"import struct; print(struct.calcsize('P') * 8)\""
  - node --version
  - which npm
  - npm --version
  - npm config get prefix
  - ruby --version
  - go version
  - conda --version

  - ps: fudge install
  - choco list --local-only
  - refreshenv
  - echo %PATH%

  - node --version
  - which npm
  - npm --version
  - npm config get prefix
  - ruby --version
  - go version
  - conda --version
  - R --version

  # Check that we have the expected version and architecture for Python
  - "python --version"
  - "python -c \"import struct; print(struct.calcsize('P') * 8)\""

  - "%MSYS_BIN%\\date.exe"

  - "%CMD_IN_ENV% python -m pip install --upgrade pip setuptools"
  - "%CMD_IN_ENV% python -m pip install tox-appveyor tox-backticks tox-venv"
  - "%MSYS_BIN%\\date.exe"

build: false  # Not a C# project, build stuff at the test step instead.

test_script:
  # Force DOS format, as Checkstyle configs enable NewlineAtEndOfFile,
  # which defaults to CRLF on Windows, and Appveyor CI ignores .gitattributes
  # http://help.appveyor.com/discussions/problems/5687-gitattributes-changes-dont-have-any-effect
  - unix2dos tests/java/test_files/CheckstyleGood.java
  # Clang DLLs x64 were nowadays installed, but the x64 version hangs, so we
  # exclude according tests. See https://github.com/appveyor/ci/issues/495 and
  # https://github.com/appveyor/ci/issues/688
  - set TOXENV=py36-noreqs-pip-npm-gem-go-perl-php-java8-win-check-noskip-codecov
  - "sed -i 's/^envlist.*$/envlist: %TOXENV%/' tox.ini"
  - "%CMD_IN_ENV% python -m tox"

matrix:
  fast_finish: true
