image: Visual Studio 2015

environment:
  global:
    PIP_CACHE_DIR: C:\pip_cache
    # Needed if pip uninstall is used
    PIP_YES: 1
    NUGET_EXE_NO_PROMPT: 1
    NUGET_HTTP_CACHE_PATH: C:\nuget_http_cache
    CHOCO_CACHE_DIR: C:\choco_cache
    PLATFORM: $(PLATFORM)
    MSYS_ROOT: C:\msys64
    MSYS_BIN: $(MSYS_ROOT)\usr\bin
    MSSDK_ROOT: C:\Program Files\Microsoft SDKs
    VS_ROOT: C:\Program Files (x86)\Microsoft Visual Studio
    VIRTUALENV_NO_DOWNLOAD: 1
    VIRTUALENV_NO_PIP: 1
    VIRTUALENV_NO_SETUPTOOLS: 1
    # Uncomment to debug tox venv problems
    # VIRTUALENV_VERBOSE: 1
    GOPATH: C:\gopath
    PATH: >-
      C:\python;C:\python\Scripts;$(PATH);$(MSYS_BIN);
      %USERPROFILE%\.nuget\packages\fudge\1.3.0\tools;
      C:\ruby\bin;
      C:\jdk\bin;
      C:\miniconda;C:\miniconda\Scripts;
      $(GOPATH)\bin;
      $(APPVEYOR_BUILD_FOLDER)\node_modules\.bin;
      $(APPVEYOR_BUILD_FOLDER)\vendor\bin;
    JL_PKG: CoalaBears
    JULIA_PROJECT: '@.'
    BEAR_LIST: astyle cppcheck xmllint
    TOX_TEST_SELECTORS: pip-noreqs-npm-gem-go-perl-php-java8-adhoc
    TOX_FEATURES: check-noskip-codecov
    TOXENV: py$(PYTHON_MINOR_NODOTS)-$(TOX_TEST_SELECTORS)-$(TOX_FEATURES)-win

  matrix:
    - PYTHON_VERSION: 3.6.8
      PYTHON_MINOR_NODOTS: 36

    - PYTHON_VERSION: 3.5.4
      PYTHON_MINOR_NODOTS: 35

    - PYTHON_VERSION: 3.4.4
      PYTHON_MINOR_NODOTS: 34

platform:
  - x64
  - x86

cache:
  - C:\nuget_http_cache
  - C:\choco_cache
  - "C:\\pip_cache"
  - "C:\\Users\\appveyor\\AppData\\Roaming\\nltk_data"
  - "%LOCALAPPDATA%\\Composer"

branches:
  except:
    - /^sils\/.*/

install:
  # Show initial state
  - python --version
  - "python -c \"import struct; print(struct.calcsize('P') * 8)\""
  - node --version
  - which npm
  - npm --version
  - npm config get prefix
  - go version
  - ruby --version
  - which java
  - java -version
  - which javac
  - javac -version
  - perl --version
  - which gcc & exit 0
  - gcc --version & exit 0
  - which cl & exit 0
  - cl & exit 0

  # Stores environment in registry, with minor tweaks
  - python .ci/fix_path.py
  - refreshenv

  - cp .ci/choco.config C:\ProgramData\chocolatey\config\chocolatey.config


  # Set up AppVeyor product versions, and install dummy choco entries for them
  - nuget install fudge -verbosity quiet
  - ps: fudge install -FudgefilePath .ci/Fudgefile.appveyor
  - choco list --local-only
  - refreshenv
  - echo %PATH%
  # Avoid tools finding and using MinGW
  - mv C:\MinGW %TEMP%
  # Avoid tools finding and using Visual Studio
  - ls -al "%MSSDK_ROOT%"
  - rm -rf "%MSSDK_ROOT%"
  - ls -al "%VS_ROOT%" & exit 0
  - rm -rf "%VS_ROOT%" & exit 0
  - ls -al "%VS_ROOT%"* & exit 0
  - rm -rf (ls "%VS_ROOT%"*) & exit 0

  # Show updated SOE; versions should be as defined in top of the Fudgefile
  - python --version
  - "python -c \"import struct; print(struct.calcsize('P') * 8)\""
  - node --version
  - which npm
  - npm --version
  - npm config get prefix
  - go version
  - ruby --version
  - which java
  - java -version
  - which javac
  - javac -version
  - perl --version
  - which gcc & exit 0
  - gcc --version & exit 0
  - conda --version

  - "%MSYS_BIN%\\date.exe"
  # Install lxml needed by for coala-bears as a wheel as libxml2 and libxslt
  # headers and library files are not available, and STATIC_DEPS=true often
  # results in linter problems due to different VS compilers and MS runtimes.
  - python -m pip install --prefer-binary lxml
  # pyrsistent->jsonschema->nbformat fails on old setuptools if no MS VC 9
  # https://github.com/tobgu/pyrsistent/issues/172
  # wrapt->astroid->pylint fails on old setuptools if no MS VC 9
  # https://github.com/GrahamDumpleton/wrapt/issues/135
  - python -m pip install -U setuptools
  - python -m pip install pyrsistent wrapt
  - python -m pip install -U six pip==9.0.3 setuptools==21.2.2

  # Install dependencies
  - python -m pip install
      --constraint bear-requirements.txt
      git+https://gitlab.com/coala/PyPrint#egg=PyPrint

  - python -m pip install
      --constraint bear-requirements.txt
      git+https://gitlab.com/coala/coala-utils#egg=coala-utils

  - python -m pip install
      --constraint bear-requirements.txt
      git+https://github.com/coala/coala#egg=coala

  - python -m pip install
      --constraint bear-requirements.txt
      -r requirements.txt

  - python -m pip install
      --constraint bear-requirements.txt
      pip==9.0.3 setuptools==21.2.2
      -e .

  - python -m pip freeze --all > constraints.txt

  - python -m pip install
      --constraint constraints.txt
      tox tox-backticks

  - "%MSYS_BIN%\\date.exe"
  # Install remainer of the Fudgefile with chocolatey using Fudge
  - ps: fudge install
  - refreshenv
  - echo %PATH%

  # Check that we have the expected version and architecture for Python
  - python --version
  - "python -c \"import struct; print(struct.calcsize('P') * 8)\""
  # Confirm other versions
  - node --version
  - which npm
  - npm --version
  - npm config get prefix
  - go version
  - ruby --version
  - perl --version
  - which java
  - java -version
  - which javac
  - javac -version
  - conda --version
  # Newly installed versions
  - which composer & exit 0
  - composer --version & exit 0
  - ppm --version & exit 0


  - "%MSYS_BIN%\\date.exe"

build: false  # Not a C# project, build stuff at the test step instead.

test_script:
  - "sed -i 's/^envlist.*$/envlist: %TOXENV%/' tox.ini"
  - python -m tox --sitepackages
  - python setup.py install

  - rm -rf .tox
  - rm -f MYMETA.yml
  - coala --ci

matrix:
  fast_finish: true
