#!/usr/bin/bash
VARS=$(Reg.exe query "HKLM\SYSTEM\CurrentControlSet\Control\Session Manager\Environment" | sed "s/[[:space:]]\+/\t/g" | tail --lines=+3 | cut -f2)
VALS=$(Reg.exe query "HKLM\SYSTEM\CurrentControlSet\Control\Session Manager\Environment" | sed "s/[[:space:]]\+/\t/g" | tail --lines=+3 | cut -f4)
#echo $VARS
SAVEIFS=$IFS
ARR1=($VARS)
ARR2=($VALS)
COUNT=${#ARR1[*]}
#read -ra ARR <<< "$VARS"
pad='                             '
for (( IDX=1 ; IDX<COUNT; IDX++ )) do
	#echo -n "${ARR1[$IDX]}"
	PAD=$(printf '%20s' ${ARR1[$IDX]})
	label=${ARR1[$IDX]}
	if [ "$label" = "USERNAME" ]; then
	  continue
	fi
	current="${!label}"
	if [ -z "$current" ]; then
	  upper_label=${label^^}
	  current="${!upper_label}"
    fi
	raw="${ARR2[$IDX]}"
	if [ -n "$current" ]; then
      if [ "$current" = "$val" ]; then
        echo $label not changed
        continue
      fi
    fi
    echo $label raw: $val
    val="$raw"
	val="${val//\\/\/}"
    echo $label fiddle 1: $val
	val="${val//\%/%%}"
	printf "$label %s $val \n" "${pad:${#label}}"
	if [ -z "$current" ]; then
	  current="${!label}"
	  printf "set new $label to $current\n"
	elif [ "$current" != "$val" ]; then
      printf "updating $label was $current\n"
      export $label="$val"
	  current="${!label}"
	  printf "updating $label now $current\n"
	fi
	#echo -n $PAD
	#echo -ne "\t"
	#echo ${ARR2[$IDX]}
  done
